# * _config.yml
# * Stores static configuration and project info
#
# * Spaces only, no tabs
# * Wrap words in quotes wherever commas are used

org:        Hyde
tracking:   UA-XXXXXXXX-X
permalink:  pretty
exclude:    [".gitignore"]
gems:
  - jekyll-seo-tag